# Generated by Django 3.2.5 on 2021-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity1', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('entity2', models.CharField(max_length=100)),
            ],
        ),
    ]
